# Generated by Django 5.2.18 on 2026-10-08 21:53

import core.fields
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoSandbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True)),
                ('role', models.CharField(help_text='Role the visitor started with', max_length=10)),
                ('ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('stamp', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(default='ODG-RESTAURANT', max_length=80)),
                ('default_language', models.CharField(choices=[('en', 'English'), ('nl', 'Nederlands'), ('es', 'Español')], default='en', max_length=5)),
                ('date_format', models.CharField(choices=[('d-m-Y', '31-12-2026'), ('d/m/Y', '31/12/2026'), ('Y-m-d', '2026-12-31'), ('j F Y', '31 December 2026')], default='d-m-Y', max_length=20)),
                ('max_managers', models.PositiveSmallIntegerField(default=2)),
                ('password_min_length', models.PositiveSmallIntegerField(default=8)),
                ('session_timeout_minutes', models.PositiveIntegerField(default=120)),
                ('max_login_attempts', models.PositiveSmallIntegerField(default=5)),
                ('lockout_minutes', models.PositiveSmallIntegerField(default=15)),
                ('smtp_enabled', models.BooleanField(default=False)),
                ('smtp_host', models.CharField(blank=True, max_length=120)),
                ('smtp_port', models.PositiveIntegerField(default=465)),
                ('smtp_security', models.CharField(choices=[('ssl', 'SSL/TLS'), ('starttls', 'STARTTLS'), ('none', 'None')], default='ssl', max_length=10)),
                ('smtp_username', models.CharField(blank=True, max_length=120)),
                ('smtp_password', core.fields.EncryptedTextField(blank=True)),
                ('smtp_from_email', models.EmailField(blank=True, max_length=254)),
                ('smtp_from_name', models.CharField(blank=True, max_length=80)),
                ('notify_by_email', models.BooleanField(default=True)),
                ('demo_enabled', models.BooleanField(default=True, help_text='Allow visitors to try the Waiter, Bartender, Chef, Manager and Owner dashboards at /demo/ without logging in.', verbose_name='Public demo')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True, default='We are working on our website. Please come back soon.')),
                ('activity_log_days', models.PositiveIntegerField(default=365)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('moderator', 'Moderator'), ('owner', 'Owner'), ('manager', 'Manager'), ('waiter', 'Waiter'), ('bartender', 'Bartender'), ('chef', 'Chef')], default='waiter', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('id_number', models.CharField(blank=True, max_length=60, verbose_name='ID number')),
                ('photo', models.ImageField(blank=True, upload_to='private/avatars/')),
                ('language', models.CharField(blank=True, choices=[('en', 'English'), ('nl', 'Nederlands'), ('es', 'Español')], max_length=5)),
                ('bio', models.TextField(blank=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('login', 'Login'), ('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('upload', 'Upload'), ('download', 'Download'), ('system', 'System')], max_length=20)),
                ('area', models.CharField(blank=True, max_length=40)),
                ('message', models.CharField(max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=30)),
                ('previous_version', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('file_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('applied', 'Applied'), ('failed', 'Failed'), ('rolled_back', 'Rolled back')], default='uploaded', max_length=20)),
                ('log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
