# Generated by Django 5.2.18 on 2026-10-08 21:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('bistro', 'Bistro'), ('modern', 'Modern'), ('lounge', 'Lounge')], default='bistro', max_length=20)),
                ('primary_color', models.CharField(default='#7a2e1d', max_length=7)),
                ('secondary_color', models.CharField(default='#c8102e', max_length=7)),
                ('accent_color', models.CharField(default='#d9a441', max_length=7)),
                ('background_color', models.CharField(default='#fbf6ee', max_length=7)),
                ('text_color', models.CharField(default='#2b211c', max_length=7)),
                ('heading_font', models.CharField(default='Playfair Display', max_length=40)),
                ('body_font', models.CharField(default='Lato', max_length=40)),
                ('base_font_size', models.PositiveSmallIntegerField(default=16)),
                ('radius', models.PositiveSmallIntegerField(default=10, help_text='Corner roundness in px')),
                ('hero_enabled', models.BooleanField(default=True)),
                ('hero_image', models.ImageField(blank=True, upload_to='public/hero/')),
                ('hero_title', models.CharField(blank=True, default='Fresh food, island flavours', max_length=160)),
                ('hero_subtitle', models.CharField(blank=True, default='Lunch and dinner with a view. Book your table online.', max_length=300)),
                ('hero_button_text', models.CharField(blank=True, default='Book a table', max_length=60)),
                ('hero_button_link', models.CharField(blank=True, default='/reservations/', max_length=255)),
                ('hero_overlay', models.PositiveSmallIntegerField(default=45, help_text='Darkening over the image, 0–90 %')),
                ('header_layout', models.CharField(choices=[('left', 'Logo left, menu right'), ('center', 'Logo centred above the menu'), ('split', 'Menu left and right of a centred logo')], default='left', max_length=10)),
                ('header_sticky', models.BooleanField(default=True)),
                ('header_topbar', models.BooleanField(default=True, help_text='Small bar with phone, e-mail and opening hours')),
                ('header_cta_text', models.CharField(blank=True, default='Book a table', max_length=40)),
                ('header_cta_link', models.CharField(blank=True, default='/reservations/', max_length=255)),
                ('footer_layout', models.JSONField(blank=True, default=dict)),
                ('footer_text', models.TextField(blank=True)),
                ('footer_show_social', models.BooleanField(default=True)),
                ('footer_show_powered', models.BooleanField(default=True)),
                ('custom_css', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Restaurant', max_length=120, verbose_name='Restaurant name')),
                ('short_name', models.CharField(blank=True, max_length=40)),
                ('motto', models.CharField(blank=True, max_length=200, verbose_name='Slogan')),
                ('logo', models.ImageField(blank=True, upload_to='public/brand/')),
                ('logo_light', models.ImageField(blank=True, help_text='Version for dark backgrounds', upload_to='public/brand/')),
                ('favicon', models.ImageField(blank=True, upload_to='public/brand/')),
                ('address', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, default='Willemstad', max_length=80)),
                ('country', models.CharField(blank=True, default='Curaçao', max_length=80)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('whatsapp', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.CharField(blank=True, max_length=120)),
                ('opening_hours', models.TextField(blank=True, default='Mon–Sun 12:00 – 22:00', help_text='Shown on the website. Booking hours are set in Settings → Reservations.')),
                ('cuisine', models.CharField(blank=True, default='Caribbean, International', help_text='For Google (schema.org)', max_length=120)),
                ('price_range', models.CharField(blank=True, default='$$', max_length=5)),
                ('map_embed_url', models.URLField(blank=True, help_text='Google Maps → Share → Embed a map → src URL', max_length=500)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('tiktok', models.URLField(blank=True)),
                ('tripadvisor', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('location', models.CharField(choices=[('header', 'Header (main menu)'), ('footer', 'Footer'), ('none', 'Not shown (use in a widget)')], default='none', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(blank=True, help_text='Defaults to the restaurant name', max_length=70)),
                ('title_separator', models.CharField(default='|', max_length=5)),
                ('meta_description', models.CharField(blank=True, max_length=170)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('default_og_image', models.ImageField(blank=True, upload_to='public/seo/')),
                ('allow_indexing', models.BooleanField(default=True, help_text='Let Google and Bing index the website')),
                ('sitemap_enabled', models.BooleanField(default=True)),
                ('robots_extra', models.TextField(blank=True, help_text='Extra lines for robots.txt')),
                ('canonical_domain', models.CharField(blank=True, help_text='e.g. https://www.myrestaurant.cw', max_length=120)),
                ('google_verification', models.CharField(blank=True, max_length=120)),
                ('bing_verification', models.CharField(blank=True, max_length=120)),
                ('google_analytics_id', models.CharField(blank=True, help_text='GA4 ID, e.g. G-XXXXXXX', max_length=30)),
                ('schema_type', models.CharField(choices=[('Restaurant', 'Restaurant'), ('BarOrPub', 'Bar or pub'), ('CafeOrCoffeeShop', 'Café / coffee shop'), ('FastFoodRestaurant', 'Fast food'), ('Bakery', 'Bakery'), ('Winery', 'Wine bar')], default='Restaurant', max_length=30)),
                ('breadcrumbs', models.BooleanField(default=True, verbose_name='Breadcrumbs (schema.org)')),
                ('redirects', models.TextField(blank=True, help_text='One per line: /old-address/ /new-address/ (permanent 301 redirect)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='public/library/%Y/%m/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('alt', models.CharField(blank=True, max_length=200, verbose_name='Alt text')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('editor', models.CharField(choices=[('builder', 'Drag & drop builder'), ('html', 'HTML editor')], default='builder', max_length=10)),
                ('layout', models.JSONField(blank=True, default=dict, help_text='Sections, columns and widgets of the builder')),
                ('content', models.TextField(blank=True, help_text='HTML of the HTML editor')),
                ('excerpt', models.TextField(blank=True)),
                ('featured_image', models.ImageField(blank=True, upload_to='public/pages/')),
                ('template', models.CharField(choices=[('default', 'Default'), ('full', 'Full width'), ('landing', 'Landing (with hero)'), ('canvas', 'Canvas (no page title)')], default='default', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('is_homepage', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=170)),
                ('focus_keyword', models.CharField(blank=True, help_text='The search term this page should be found with', max_length=80)),
                ('og_image', models.ImageField(blank=True, upload_to='public/pages/')),
                ('noindex', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='website.page')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('url', models.CharField(blank=True, help_text='Used when no page is chosen', max_length=255)),
                ('new_tab', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='website.menu')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='website.menuitem')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.page')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PageRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('layout', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='website.page')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
