# Generated by Django 5.2.18 on 2026-10-09 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seosettings',
            name='schema_type',
            field=models.CharField(choices=[('Restaurant', 'Restaurant'), ('BarOrPub', 'Bar or pub'), ('CafeOrCoffeeShop', 'Café / coffee shop'), ('FastFoodRestaurant', 'Fast food'), ('Bakery', 'Bakery'), ('Winery', 'Wine bar'), ('Organization', 'Company (not a restaurant)')], default='Restaurant', max_length=30),
        ),
    ]
