# Generated by Django 5.2.18 on 2026-10-08 21:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('category', models.CharField(choices=[('food', 'Food purchases'), ('drinks', 'Drink purchases'), ('wages', 'Wages & salaries'), ('rent', 'Rent'), ('utilities', 'Water, electricity & internet'), ('maintenance', 'Maintenance & repairs'), ('marketing', 'Marketing'), ('fees', 'Bank & card fees'), ('taxes', 'Taxes & licences'), ('other', 'Other')], default='food', max_length=12)),
                ('description', models.CharField(max_length=200)),
                ('supplier', models.CharField(blank=True, max_length=120)),
                ('invoice_number', models.CharField(blank=True, max_length=60)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total paid, including OB', max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='OB included')),
                ('method', models.CharField(choices=[('bank', 'Bank transfer'), ('cash', 'Cash'), ('card', 'Card')], default='bank', max_length=5)),
                ('receipt', models.FileField(blank=True, upload_to='private/receipts/%Y/%m/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
